services:
  voice_service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_DIR: voice_service
    ports:
      - "8080:8080"
    volumes:
      - ./voice_service:/app
    command: ["python", "app.py"]
    env_file:
      - .env

  summary_service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_DIR: summary_service
    volumes:
      - ./summary_service:/app
    env_file:
      - .env

volumes:
  reports:
